### ISSUE TITLE
No way to customize failure messages

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-rackunit#2]
`message` parameters of checks are ignored.
I'd like parameters passed to a solution be printed in case of failure. Now it can be done for all test cases or it can be done with double checking and logging before a real check, both of which don't look too good.

**Comment by yfzhe** [comment]
As I said before, there are some inconsistency about `check-info` stack. Rackunit would raise an instance of `exn:test:check` error type, which contains some `check-info`, when a test-case failed. However, if something (just get it a name v) raised while a test run,  v is the error we catch. You can find no `check-info` around v.

If we just ignore this inconsistency, make this wrapper works like `rackunit/text-ui`. There are still some discuss space:
1) It seems to me that Codewars format support table mode. So what format the `check-info`s would be presented in? Plain text or table mode?
2) Which check-info should we print? 'actual, 'except, and 'message? Or print all the `check-info`s provided. The former lacks more customize ability, while the later looks too verbose.

**Comment by kazk** [comment]
Some links to documentation and sources for convenience:

> RackUnit provides an API for running tests, from which custom UIs can be created.
> [Programmatically Running Tests and Inspecting Results](https://docs.racket-lang.org/rackunit/internals.html#%28part._running%29)

> When a check fails, it may add information about the failure to RackUnit’s [check-info stack](https://docs.racket-lang.org/rackunit/api.html#%28tech._check._info._stack%29). Additional information can be stored by using the [`with-check-info*`](https://docs.racket-lang.org/rackunit/api.html#%28def._%28%28lib._rackunit%2Fmain..rkt%29._with-check-info%2A%29%29) function, and the [`with-check-info`](https://docs.racket-lang.org/rackunit/api.html#%28form._%28%28lib._rackunit%2Fmain..rkt%29._with-check-info%29%29) macro.
> [Augmenting Information on Check Failure](https://docs.racket-lang.org/rackunit/api.html#%28part._.Augmenting_.Information_on_.Check_.Failure%29)

- [`rackunit/private/check-info`](https://github.com/racket/rackunit/blob/5fc1ec71fa7ba9cc7d4d20f8a5136fc5d190da5d/rackunit-lib/rackunit/private/check-info.rkt)
- [`rackunit/private/format`](https://github.com/racket/rackunit/blob/5fc1ec71fa7ba9cc7d4d20f8a5136fc5d190da5d/rackunit-lib/rackunit/private/format.rkt) provides `display-test-result` etc that might be useful.
- [`rackunit/text-ui`](https://github.com/racket/rackunit/blob/5fc1ec71fa7ba9cc7d4d20f8a5136fc5d190da5d/rackunit-lib/rackunit/text-ui.rkt)

**Comment by yfzhe** [comment]
I agree this would be an enhancement if we use the `check-info`s as more as possible. Yesterday, I tried to print all the `check-info`s in `run-tests`. It seems really too verbose, like this: 

```
name:        check-eq?
location:    test.rkt:18:14
expression:  (check-eq? 1 "string")
params:      '(1 "string")
actual:      1
expected:    "string"
```

Maybe adding a mode argument to the `run-tests` procedure like what [`run-tests`](https://docs.racket-lang.org/rackunit/api.html#(def._((lib._rackunit%2Ftext-ui..rkt)._run-tests))) in `rackunit/text-ui` does is good.

**Comment by kazk** [comment]
For now, we should be able to simply include `message` if it's there.

When
```racket
(check-equal? (add 1 1) 2 "a = 1, b = 1")
```
fails, `check-info` stack has the following information:
```
message:    "a = 1, b = 1"
actual:     0
expected:   2
```

To improve further, we can derive something from [`display-test-failure/error`](https://github.com/racket/rackunit/blob/5fc1ec71fa7ba9cc7d4d20f8a5136fc5d190da5d/rackunit-lib/rackunit/private/format.rkt#L113).

**Comment by yfzhe** [comment]
Sorry, I missed the message `check-info`. I thought `check-`s only have two arguments:( A little fix is coming.

**Comment by kazk** [comment]
I'll close this when #3 is deployed.

**Comment by kazk** [comment]
Deployed #3 and #4
